name: Build and Deploy to Hosting

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build
        env:
          VITE_API_URL: https://spark-tech-server.vercel.app/api/v1

      - name: Deploy BestBuy4uBd
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_HOST_A }}
          username: ${{ secrets.FTP_USERNAME_A }}
          password: ${{ secrets.FTP_PASSWORD_A }}
          port: 21
          local-dir: dist/
          server-dir: /
          dangerous-clean-slate: false

      - name: Deploy NeedOnlineShop
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_HOST_C }}
          username: ${{ secrets.FTP_USERNAME_C }}
          password: ${{ secrets.FTP_PASSWORD_C }}
          port: 21
          local-dir: dist/
          server-dir: /
          dangerous-clean-slate: false
